#!/bin/bash
sudo $1 install build-essential -y
sudo $1  install bison -y
sudo $1  install flex -y
sudo $1  install libgmp3-dev -y
sudo $1  install libmpc-dev -y
sudo $1  install libmpfr-dev -y
sudo $1  install texinfo -y
sudo $1  install libcloog-isl-dev -y
sudo $1  install libisl-dev -y
sudo $1  install qemu  -y
sudo $1  install grub-common -y
sudo $1  install xorriso -y
sudo $1  install nasm -y
sudo $1  install grub-pc-bin -y
sudo $1  install libfontconfig1 -y
sudo $1 install mesa-common-dev -y
sudo $1  install libglu1-mesa-dev -y
sudo $1 update && sudo $1 upgrade -y
clear
echo -e "if not RUN ! \nenter your package manager \nlike this 'gccCrossCompiler (yum or apt)'"
sleep 10;
