#!/bin/bash
sudo apt install build-essential -y
sudo apt  install bison -y
sudo apt  install flex -y
sudo apt  install libgmp3-dev -y
sudo apt  install libmpc-dev -y
sudo apt  install libmpfr-dev -y
sudo apt  install texinfo -y
sudo apt  install libisl-dev -y
sudo apt  install qemu  -y
sudo apt  install grub-common -y
sudo apt  install xorriso -y
sudo apt  install nasm -y
sudo apt  install grub-pc-bin -y
sudo apt  install libfontconfig1 -y
sudo apt install mesa-common-dev -y
sudo apt  install libglu1-mesa-dev -y
sudo apt update && sudo apt upgrade -y
sudo apt install qemu-system-x86 -y

